### ISSUE TITLE
Add support for Java 10 and deprecate 9

### ISSUE THREAD

**Issue by EtienneM** [Scalingo/java-buildpack#1]
According to Wikipedia:

> Java 8 is still supported but there will be no more security updates for Java 9. Versions earlier than Java 8 are supported by companies on a commercial basis

https://en.wikipedia.org/wiki/Java_(programming_language)

Maybe we should remove support for Java 7 and before?

**Comment by EtienneM** [comment]
@Soulou answered on Slack:

> Nonde don't drop support like this
From Java 6 to 10 is handled by the buildpack

**Comment by brandon-welsch** [comment]
This is handled by https://github.com/Scalingo/buildpack-jvm-common. Java 10 and new releases is currently supported. Java 8 is not dropped.
