### ISSUE TITLE
[Maven] Support 3.6.3 and 3.9.4 versions

### ISSUE THREAD

**Issue by brandon-welsch** [Scalingo/java-buildpack#8]
https://maven.apache.org/docs/history.html

Currently the archives for these versions are not available in the bucket we use:
- https://lang-jvm.s3.us-east-1.amazonaws.com/maven-3.6.3.tar.gz
- https://lang-jvm.s3.us-east-1.amazonaws.com/maven-3.8.8.tar.gz

We should wait for it.

**Comment by Frzk** [comment]
There is also a `3.9.3` version.

Anyway, it seems that upstream doesn't update this buildpack anymore and the packages are not available (as of july 2023).

**Comment by ipfaze** [comment]
It seems that upstream does still update this buildpack, they release V73 which use by default Maven 3.9.4.
https://github.com/heroku/heroku-buildpack-java/commit/3424ddb215568d2ab5ccf4ca50dfb247d3a94419

As it was opened more than 6 months, I'm raising the priority from `low` to `high`.
